language: java
before_install:
    - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev libpng-dev
    - make clean -C C-Genetics/libs/AntTweakBar/src
    - make -C C-Genetics/libs/AntTweakBar/src
    - make clean -C C-Genetics
    - make -C C-Genetics

script: mvn test