language: java
before_install:
    - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev libpng-dev
    - cd C-Genetics/libs/AntTweakBar/src
    - make clean
    - make
    - cd ../../..
    - make clean
    - make
    - cd